### ISSUE TITLE
Exception: net.sf.saxon.s9api.SaxonApiException: The supplied file does not appear to be a stylesheet

### ISSUE THREAD

**Issue by harmeetsingh0013** [etsy/sbt-checkstyle-plugin#24]
I am using ```checkstyle 7.1 version``` with this plugin. ```sbt checkstyle``` command run file and generate report into xml successfully. But when i am using xslt trasnforamtion from xml to html, i am getting following error: 

```
Error at checkstyle on line 2 column 27 of checkstyle-report.xml:
  XTSE0150: The supplied file does not appear to be a stylesheet
net.sf.saxon.s9api.SaxonApiException: The supplied file does not appear to be a stylesheet
	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:546)
	at com.etsy.sbt.checkstyle.Checkstyle$$anonfun$applyXSLT$1.apply(Checkstyle.scala:112)
	at com.etsy.sbt.checkstyle.Checkstyle$$anonfun$applyXSLT$1.apply(Checkstyle.scala:109)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:74)
	at com.etsy.sbt.checkstyle.Checkstyle$.applyXSLT(Checkstyle.scala:109)
	at com.etsy.sbt.checkstyle.Checkstyle$.checkstyle(Checkstyle.scala:56)
	at com.etsy.sbt.checkstyle.CheckstylePlugin$autoImport$$anonfun$checkstyleTask$1.apply(CheckstylePlugin.scala:35)
	at com.etsy.sbt.checkstyle.CheckstylePlugin$autoImport$$anonfun$checkstyleTask$1.apply(CheckstylePlugin.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
-----------------------------------------------------
```

**Comment by ajsquared** [comment]
Can you share the xslt file you are using and any configuration changes you've made for this plugin in your build definition?

**Comment by harmeetsingh0013** [comment]
Hey @ajsquared i found the problem. ```CheckstyleXSLTSettings``` constructor, we need to pass first argument of style xslt, but i am passing generated report file. Thanks for your reply.

**Comment by ajsquared** [comment]
Great, glad it's worked out!
